server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 16379
    password: mypass
    database: 0